version: "3.9" 
services:
  postgis:
    image: mdillon/postgis:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
    - 5432:5432


